name: yucheng_ble_example
description: "Demonstrates how to use the yucheng_ble plugin."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter

  yucheng_ble:
    path: ../
  cupertino_icons: ^1.0.8
  permission_handler: ^11.4.0

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
