name: yucheng_ble
description: "Plugin for yucheng"
version: 0.0.40
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  pigeon: ^25.3.0

flutter:

  plugin:
    platforms:
      android:
        package: com.crefter.yuchengplugin.yucheng_ble
        pluginClass: YuchengBlePlugin
      ios:
        pluginClass: YuchengBlePlugin
