// Autogenerated from Pigeon (v25.1.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}
bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
        .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    final Iterable<Object?> keys = (a as Map<Object?, Object?>).keys;
    return a.length == b.length && keys.every((Object? key) =>
        (b as Map<Object?, Object?>).containsKey(key) &&
        _deepEquals(a[key], b[key]));
  }
  return a == b;
}
    

enum YuchengSleepType {
  rem,
  deep,
  awake,
  light,
  unknown,
}

enum YuchengProductState {
  unknown,
  connected,
  connectedFailed,
  disconnected,
  unavailable,
  timeOut,
}

sealed class YuchengSleepEvent {
}

/// Старый формат в минутах
class YuchengSleepDataMinutes {
  YuchengSleepDataMinutes({
    required this.deepSleepMinutes,
    required this.remSleepMinutes,
    required this.lightSleepMinutes,
  });

  int deepSleepMinutes;

  int remSleepMinutes;

  int lightSleepMinutes;

  List<Object?> _toList() {
    return <Object?>[
      deepSleepMinutes,
      remSleepMinutes,
      lightSleepMinutes,
    ];
  }

  Object encode() {
    return _toList();  }

  static YuchengSleepDataMinutes decode(Object result) {
    result as List<Object?>;
    return YuchengSleepDataMinutes(
      deepSleepMinutes: result[0]! as int,
      remSleepMinutes: result[1]! as int,
      lightSleepMinutes: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! YuchengSleepDataMinutes || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return 
      deepSleepMinutes == other.deepSleepMinutes
      && remSleepMinutes == other.remSleepMinutes
      && lightSleepMinutes == other.lightSleepMinutes;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

/// Если deepSleepCount == 0xFFFF, то новый формат в секундах
class YuchengSleepDataSeconds {
  YuchengSleepDataSeconds({
    required this.deepSleepSeconds,
    required this.remSleepSeconds,
    required this.lightSleepSeconds,
  });

  int deepSleepSeconds;

  int remSleepSeconds;

  int lightSleepSeconds;

  List<Object?> _toList() {
    return <Object?>[
      deepSleepSeconds,
      remSleepSeconds,
      lightSleepSeconds,
    ];
  }

  Object encode() {
    return _toList();  }

  static YuchengSleepDataSeconds decode(Object result) {
    result as List<Object?>;
    return YuchengSleepDataSeconds(
      deepSleepSeconds: result[0]! as int,
      remSleepSeconds: result[1]! as int,
      lightSleepSeconds: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! YuchengSleepDataSeconds || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return 
      deepSleepSeconds == other.deepSleepSeconds
      && remSleepSeconds == other.remSleepSeconds
      && lightSleepSeconds == other.lightSleepSeconds;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class YuchengSleepDataEvent extends YuchengSleepEvent {
  YuchengSleepDataEvent({
    required this.startTimeStamp,
    required this.endTimeStamp,
    required this.deepSleepCount,
    required this.lightSleepCount,
    this.minutes,
    this.seconds,
    required this.details,
  });

  /// Начало сна в мс
  int startTimeStamp;

  /// Конец сна в мс
  int endTimeStamp;

  /// Если равен 0xFFFF, то новый формат в секундах, иначе старый в минутах
  int deepSleepCount;

  int lightSleepCount;

  /// Старый формат, если [deepSleepCount] != 0xFFFF
  YuchengSleepDataMinutes? minutes;

  /// Новый формат, если [deepSleepCount] == 0xFFFF
  YuchengSleepDataSeconds? seconds;

  List<YuchengSleepDataDetail> details;

  List<Object?> _toList() {
    return <Object?>[
      startTimeStamp,
      endTimeStamp,
      deepSleepCount,
      lightSleepCount,
      minutes,
      seconds,
      details,
    ];
  }

  Object encode() {
    return _toList();  }

  static YuchengSleepDataEvent decode(Object result) {
    result as List<Object?>;
    return YuchengSleepDataEvent(
      startTimeStamp: result[0]! as int,
      endTimeStamp: result[1]! as int,
      deepSleepCount: result[2]! as int,
      lightSleepCount: result[3]! as int,
      minutes: result[4] as YuchengSleepDataMinutes?,
      seconds: result[5] as YuchengSleepDataSeconds?,
      details: (result[6] as List<Object?>?)!.cast<YuchengSleepDataDetail>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! YuchengSleepDataEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return 
      startTimeStamp == other.startTimeStamp
      && endTimeStamp == other.endTimeStamp
      && deepSleepCount == other.deepSleepCount
      && lightSleepCount == other.lightSleepCount
      && minutes == other.minutes
      && seconds == other.seconds
      && _deepEquals(details, other.details);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class YuchengSleepDataDetail {
  YuchengSleepDataDetail({
    required this.startTimeStamp,
    required this.duration,
    required this.type,
  });

  /// Начало в мс
  int startTimeStamp;

  /// Длительность в мс
  int duration;

  /// Тип сна
  YuchengSleepType type;

  List<Object?> _toList() {
    return <Object?>[
      startTimeStamp,
      duration,
      type,
    ];
  }

  Object encode() {
    return _toList();  }

  static YuchengSleepDataDetail decode(Object result) {
    result as List<Object?>;
    return YuchengSleepDataDetail(
      startTimeStamp: result[0]! as int,
      duration: result[1]! as int,
      type: result[2]! as YuchengSleepType,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! YuchengSleepDataDetail || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return 
      startTimeStamp == other.startTimeStamp
      && duration == other.duration
      && type == other.type;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class YuchengSleepErrorEvent extends YuchengSleepEvent {
  YuchengSleepErrorEvent({
    required this.error,
  });

  String error;

  List<Object?> _toList() {
    return <Object?>[
      error,
    ];
  }

  Object encode() {
    return _toList();  }

  static YuchengSleepErrorEvent decode(Object result) {
    result as List<Object?>;
    return YuchengSleepErrorEvent(
      error: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! YuchengSleepErrorEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return 
      error == other.error;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

sealed class YuchengProductStateEvent {
}

class YuchengProductStateDataEvent extends YuchengProductStateEvent {
  YuchengProductStateDataEvent({
    required this.state,
  });

  YuchengProductState state;

  List<Object?> _toList() {
    return <Object?>[
      state,
    ];
  }

  Object encode() {
    return _toList();  }

  static YuchengProductStateDataEvent decode(Object result) {
    result as List<Object?>;
    return YuchengProductStateDataEvent(
      state: result[0]! as YuchengProductState,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! YuchengProductStateDataEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return 
      state == other.state;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class YuchengProductStateErrorEvent extends YuchengProductStateEvent {
  YuchengProductStateErrorEvent({
    required this.state,
    required this.error,
  });

  YuchengProductState state;

  String error;

  List<Object?> _toList() {
    return <Object?>[
      state,
      error,
    ];
  }

  Object encode() {
    return _toList();  }

  static YuchengProductStateErrorEvent decode(Object result) {
    result as List<Object?>;
    return YuchengProductStateErrorEvent(
      state: result[0]! as YuchengProductState,
      error: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! YuchengProductStateErrorEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return 
      state == other.state
      && error == other.error;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class YuchengDevice {
  YuchengDevice({
    required this.index,
    required this.deviceName,
    required this.uuid,
    required this.isCurrentConnected,
  });

  int index;

  String deviceName;

  String uuid;

  /// true - уже изначально подключен
  /// false - не был подключен изначально, нужно подключить
  bool isCurrentConnected;

  List<Object?> _toList() {
    return <Object?>[
      index,
      deviceName,
      uuid,
      isCurrentConnected,
    ];
  }

  Object encode() {
    return _toList();  }

  static YuchengDevice decode(Object result) {
    result as List<Object?>;
    return YuchengDevice(
      index: result[0]! as int,
      deviceName: result[1]! as String,
      uuid: result[2]! as String,
      isCurrentConnected: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! YuchengDevice || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return 
      index == other.index
      && deviceName == other.deviceName
      && uuid == other.uuid
      && isCurrentConnected == other.isCurrentConnected;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

sealed class YuchengDeviceEvent {
}

class YuchengDeviceDataEvent extends YuchengDeviceEvent {
  YuchengDeviceDataEvent({
    required this.index,
    required this.mac,
    this.isCurrentConnected,
    required this.deviceName,
  });

  int index;

  /// ДЛЯ ANDROID
  /// Нужен, чтобы подключиться к девайсу
  /// ДЛЯ IOS
  /// Uuid девайса
  String mac;

  /// Только IOS
  /// true - уже изначально подключен
  /// false - не был подключен изначально, нужно подключить
  bool? isCurrentConnected;

  String deviceName;

  List<Object?> _toList() {
    return <Object?>[
      index,
      mac,
      isCurrentConnected,
      deviceName,
    ];
  }

  Object encode() {
    return _toList();  }

  static YuchengDeviceDataEvent decode(Object result) {
    result as List<Object?>;
    return YuchengDeviceDataEvent(
      index: result[0]! as int,
      mac: result[1]! as String,
      isCurrentConnected: result[2] as bool?,
      deviceName: result[3]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! YuchengDeviceDataEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return 
      index == other.index
      && mac == other.mac
      && isCurrentConnected == other.isCurrentConnected
      && deviceName == other.deviceName;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}

class YuchengDeviceCompleteEvent extends YuchengDeviceEvent {
  YuchengDeviceCompleteEvent({
    required this.completed,
  });

  bool completed;

  List<Object?> _toList() {
    return <Object?>[
      completed,
    ];
  }

  Object encode() {
    return _toList();  }

  static YuchengDeviceCompleteEvent decode(Object result) {
    result as List<Object?>;
    return YuchengDeviceCompleteEvent(
      completed: result[0]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! YuchengDeviceCompleteEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return 
      completed == other.completed;
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList())
;
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is YuchengSleepType) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is YuchengProductState) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is YuchengSleepDataMinutes) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is YuchengSleepDataSeconds) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is YuchengSleepDataEvent) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is YuchengSleepDataDetail) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is YuchengSleepErrorEvent) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is YuchengProductStateDataEvent) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is YuchengProductStateErrorEvent) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is YuchengDevice) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is YuchengDeviceDataEvent) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is YuchengDeviceCompleteEvent) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : YuchengSleepType.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : YuchengProductState.values[value];
      case 131: 
        return YuchengSleepDataMinutes.decode(readValue(buffer)!);
      case 132: 
        return YuchengSleepDataSeconds.decode(readValue(buffer)!);
      case 133: 
        return YuchengSleepDataEvent.decode(readValue(buffer)!);
      case 134: 
        return YuchengSleepDataDetail.decode(readValue(buffer)!);
      case 135: 
        return YuchengSleepErrorEvent.decode(readValue(buffer)!);
      case 136: 
        return YuchengProductStateDataEvent.decode(readValue(buffer)!);
      case 137: 
        return YuchengProductStateErrorEvent.decode(readValue(buffer)!);
      case 138: 
        return YuchengDevice.decode(readValue(buffer)!);
      case 139: 
        return YuchengDeviceDataEvent.decode(readValue(buffer)!);
      case 140: 
        return YuchengDeviceCompleteEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());

class YuchengHostApi {
  /// Constructor for [YuchengHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  YuchengHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// [scanTimeInMs] - сколько по времени сканировать (по умолчанию 3 секунды для ios и 10 для андройд)
  /// Прослушивать стрим devices
  ///
  /// Перед сканированием нужно проверить, включен ли bluetooth и запросить разрешения
  /// на bluetooth
  Future<void> startScanDevices(double? scanTimeInSeconds) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.yucheng_ble.YuchengHostApi.startScanDevices$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[scanTimeInSeconds]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// [device] - девайс, который нужно проверить
  /// Проверяет, подключен ли данный девайс
  Future<bool> isDeviceConnected(YuchengDevice device) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.yucheng_ble.YuchengHostApi.isDeviceConnected$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[device]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Подключить девайс к сдк
  Future<bool> connect(YuchengDevice? device) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.yucheng_ble.YuchengHostApi.connect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[device]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// Отключить девайс от сдк
  Future<void> disconnect() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.yucheng_ble.YuchengHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// Запрос на получение данных о сне
  /// Можно также прослушивать стрим sleepData
  Future<List<YuchengSleepEvent?>> getSleepData() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.yucheng_ble.YuchengHostApi.getSleepData$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as List<Object?>?)!.cast<YuchengSleepEvent?>();
    }
  }

  /// ТОЛЬКО IOS
  /// Возвращает текущий подключенный девайс
  /// Если девайс был подключен до этого и не был отключен, то сдк пытается подключиться
  /// к девайсу повторно и возвращает его
  Future<YuchengDevice?> getCurrentConnectedDevice() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.yucheng_ble.YuchengHostApi.getCurrentConnectedDevice$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as YuchengDevice?);
    }
  }
}

Stream<YuchengDeviceEvent> devices( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel devicesChannel =
      EventChannel('dev.flutter.pigeon.yucheng_ble.YuchengStreamApi.devices$instanceName', pigeonMethodCodec);
  return devicesChannel.receiveBroadcastStream().map((dynamic event) {
    return event as YuchengDeviceEvent;
  });
}
    
Stream<YuchengSleepEvent> sleepData( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel sleepDataChannel =
      EventChannel('dev.flutter.pigeon.yucheng_ble.YuchengStreamApi.sleepData$instanceName', pigeonMethodCodec);
  return sleepDataChannel.receiveBroadcastStream().map((dynamic event) {
    return event as YuchengSleepEvent;
  });
}
    
Stream<YuchengProductStateEvent> deviceState( {String instanceName = ''}) {
  if (instanceName.isNotEmpty) {
    instanceName = '.$instanceName';
  }
  final EventChannel deviceStateChannel =
      EventChannel('dev.flutter.pigeon.yucheng_ble.YuchengStreamApi.deviceState$instanceName', pigeonMethodCodec);
  return deviceStateChannel.receiveBroadcastStream().map((dynamic event) {
    return event as YuchengProductStateEvent;
  });
}
    
