// Autogenerated from Pigeon (v25.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()
private fun deepEqualsYuchengBleApi(a: Any?, b: Any?): Boolean {
  if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
  }
  if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
  }
  if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
  }
  if (a is DoubleArray && b is DoubleArray) {
      return a.contentEquals(b)
  }
  if (a is Array<*> && b is Array<*>) {
    return a.size == b.size &&
        a.indices.all{ deepEqualsYuchengBleApi(a[it], b[it]) }
  }
  if (a is List<*> && b is List<*>) {
    return a.size == b.size &&
        a.indices.all{ deepEqualsYuchengBleApi(a[it], b[it]) }
  }
  if (a is Map<*, *> && b is Map<*, *>) {
    return a.size == b.size && a.all {
        (b as Map<Any?, Any?>).containsKey(it.key) &&
        deepEqualsYuchengBleApi(it.value, b[it.key])
    }
  }
  return a == b
}
    

enum class YuchengSleepType(val raw: Int) {
  REM(0),
  DEEP(1),
  AWAKE(2),
  LIGHT(3),
  UNKNOWN(4);

  companion object {
    fun ofRaw(raw: Int): YuchengSleepType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class YuchengDeviceState(val raw: Int) {
  UNKNOWN(0),
  CONNECTED(1),
  CONNECTED_FAILED(2),
  DISCONNECTED(3),
  UNAVAILABLE(4),
  READ_WRITE_OK(5),
  TIME_OUT(6);

  companion object {
    fun ofRaw(raw: Int): YuchengDeviceState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengSleepData (
  /** Начало сна в мс */
  val startTimeStamp: Long,
  /** Конец сна в мс */
  val endTimeStamp: Long,
  /** Если равен 0xFFFF, то новый формат в секундах, иначе старый в минутах */
  val deepCount: Long,
  val lightCount: Long,
  val awakeCount: Long,
  val deepInSeconds: Long,
  val remInSeconds: Long,
  val lightInSeconds: Long,
  val awakeInSeconds: Long,
  val details: List<YuchengSleepDataDetail>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengSleepData {
      val startTimeStamp = pigeonVar_list[0] as Long
      val endTimeStamp = pigeonVar_list[1] as Long
      val deepCount = pigeonVar_list[2] as Long
      val lightCount = pigeonVar_list[3] as Long
      val awakeCount = pigeonVar_list[4] as Long
      val deepInSeconds = pigeonVar_list[5] as Long
      val remInSeconds = pigeonVar_list[6] as Long
      val lightInSeconds = pigeonVar_list[7] as Long
      val awakeInSeconds = pigeonVar_list[8] as Long
      val details = pigeonVar_list[9] as List<YuchengSleepDataDetail>
      return YuchengSleepData(startTimeStamp, endTimeStamp, deepCount, lightCount, awakeCount, deepInSeconds, remInSeconds, lightInSeconds, awakeInSeconds, details)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      startTimeStamp,
      endTimeStamp,
      deepCount,
      lightCount,
      awakeCount,
      deepInSeconds,
      remInSeconds,
      lightInSeconds,
      awakeInSeconds,
      details,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengSleepData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengHealthData (
  val heartValue: Long,
  val hrvValue: Long,
  val cvrrValue: Long,
  val OOValue: Long,
  val stepValue: Long,
  val DBPValue: Long,
  val tempIntValue: Long,
  val tempFloatValue: Long,
  val startTimestamp: Long,
  val SBPValue: Long,
  val respiratoryRateValue: Long,
  val bodyFatIntValue: Long,
  val bodyFatFloatValue: Long,
  val bloodSugarValue: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengHealthData {
      val heartValue = pigeonVar_list[0] as Long
      val hrvValue = pigeonVar_list[1] as Long
      val cvrrValue = pigeonVar_list[2] as Long
      val OOValue = pigeonVar_list[3] as Long
      val stepValue = pigeonVar_list[4] as Long
      val DBPValue = pigeonVar_list[5] as Long
      val tempIntValue = pigeonVar_list[6] as Long
      val tempFloatValue = pigeonVar_list[7] as Long
      val startTimestamp = pigeonVar_list[8] as Long
      val SBPValue = pigeonVar_list[9] as Long
      val respiratoryRateValue = pigeonVar_list[10] as Long
      val bodyFatIntValue = pigeonVar_list[11] as Long
      val bodyFatFloatValue = pigeonVar_list[12] as Long
      val bloodSugarValue = pigeonVar_list[13] as Long
      return YuchengHealthData(heartValue, hrvValue, cvrrValue, OOValue, stepValue, DBPValue, tempIntValue, tempFloatValue, startTimestamp, SBPValue, respiratoryRateValue, bodyFatIntValue, bodyFatFloatValue, bloodSugarValue)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      heartValue,
      hrvValue,
      cvrrValue,
      OOValue,
      stepValue,
      DBPValue,
      tempIntValue,
      tempFloatValue,
      startTimestamp,
      SBPValue,
      respiratoryRateValue,
      bodyFatIntValue,
      bodyFatFloatValue,
      bloodSugarValue,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengHealthData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengSleepHealthData (
  val sleepData: List<YuchengSleepData>,
  val healthData: List<YuchengHealthData>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengSleepHealthData {
      val sleepData = pigeonVar_list[0] as List<YuchengSleepData>
      val healthData = pigeonVar_list[1] as List<YuchengHealthData>
      return YuchengSleepHealthData(sleepData, healthData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sleepData,
      healthData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengSleepHealthData) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class YuchengSleepEvent 
/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengSleepTimeOutEvent (
  val isTimeout: Boolean
) : YuchengSleepEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengSleepTimeOutEvent {
      val isTimeout = pigeonVar_list[0] as Boolean
      return YuchengSleepTimeOutEvent(isTimeout)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isTimeout,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengSleepTimeOutEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengSleepDataEvent (
  val sleepData: YuchengSleepData
) : YuchengSleepEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengSleepDataEvent {
      val sleepData = pigeonVar_list[0] as YuchengSleepData
      return YuchengSleepDataEvent(sleepData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sleepData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengSleepDataEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengSleepDataDetail (
  /** Начало в мс */
  val startTimeStamp: Long,
  /** Длительность в мс */
  val duration: Long,
  /** Тип сна */
  val type: YuchengSleepType
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengSleepDataDetail {
      val startTimeStamp = pigeonVar_list[0] as Long
      val duration = pigeonVar_list[1] as Long
      val type = pigeonVar_list[2] as YuchengSleepType
      return YuchengSleepDataDetail(startTimeStamp, duration, type)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      startTimeStamp,
      duration,
      type,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengSleepDataDetail) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengSleepErrorEvent (
  val error: String
) : YuchengSleepEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengSleepErrorEvent {
      val error = pigeonVar_list[0] as String
      return YuchengSleepErrorEvent(error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengSleepErrorEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class YuchengDeviceStateEvent 
/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengDeviceStateTimeOutEvent (
  val isTimeout: Boolean
) : YuchengDeviceStateEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengDeviceStateTimeOutEvent {
      val isTimeout = pigeonVar_list[0] as Boolean
      return YuchengDeviceStateTimeOutEvent(isTimeout)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isTimeout,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengDeviceStateTimeOutEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengDeviceStateDataEvent (
  val state: YuchengDeviceState
) : YuchengDeviceStateEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengDeviceStateDataEvent {
      val state = pigeonVar_list[0] as YuchengDeviceState
      return YuchengDeviceStateDataEvent(state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengDeviceStateDataEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengDeviceStateErrorEvent (
  val state: YuchengDeviceState,
  val error: String
) : YuchengDeviceStateEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengDeviceStateErrorEvent {
      val state = pigeonVar_list[0] as YuchengDeviceState
      val error = pigeonVar_list[1] as String
      return YuchengDeviceStateErrorEvent(state, error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      state,
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengDeviceStateErrorEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengDevice (
  val index: Long,
  val deviceName: String,
  /**
   * Android - тут mac address для подключения
   * IOS - uuid девайса
   */
  val uuid: String,
  /**
   * true - уже изначально подключен
   * false - не был подключен изначально, нужно подключить
   */
  val isCurrentConnected: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengDevice {
      val index = pigeonVar_list[0] as Long
      val deviceName = pigeonVar_list[1] as String
      val uuid = pigeonVar_list[2] as String
      val isCurrentConnected = pigeonVar_list[3] as Boolean
      return YuchengDevice(index, deviceName, uuid, isCurrentConnected)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      index,
      deviceName,
      uuid,
      isCurrentConnected,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengDevice) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class YuchengDeviceEvent 
/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengDeviceTimeOutEvent (
  val isTimeout: Boolean
) : YuchengDeviceEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengDeviceTimeOutEvent {
      val isTimeout = pigeonVar_list[0] as Boolean
      return YuchengDeviceTimeOutEvent(isTimeout)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isTimeout,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengDeviceTimeOutEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengDeviceDataEvent (
  val index: Long,
  /**
   * ДЛЯ ANDROID
   * Нужен, чтобы подключиться к девайсу
   */
  val mac: String,
  /**
   * Только IOS
   * true - уже изначально подключен
   * false - не был подключен изначально, нужно подключить
   */
  val isCurrentConnected: Boolean? = null,
  val deviceName: String
) : YuchengDeviceEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengDeviceDataEvent {
      val index = pigeonVar_list[0] as Long
      val mac = pigeonVar_list[1] as String
      val isCurrentConnected = pigeonVar_list[2] as Boolean?
      val deviceName = pigeonVar_list[3] as String
      return YuchengDeviceDataEvent(index, mac, isCurrentConnected, deviceName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      index,
      mac,
      isCurrentConnected,
      deviceName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengDeviceDataEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengDeviceCompleteEvent (
  val completed: Boolean
) : YuchengDeviceEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengDeviceCompleteEvent {
      val completed = pigeonVar_list[0] as Boolean
      return YuchengDeviceCompleteEvent(completed)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      completed,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengDeviceCompleteEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class YuchengHealthEvent 
/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengHealthDataEvent (
  val healthData: YuchengHealthData
) : YuchengHealthEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengHealthDataEvent {
      val healthData = pigeonVar_list[0] as YuchengHealthData
      return YuchengHealthDataEvent(healthData)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      healthData,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengHealthDataEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengHealthErrorEvent (
  val error: String
) : YuchengHealthEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengHealthErrorEvent {
      val error = pigeonVar_list[0] as String
      return YuchengHealthErrorEvent(error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengHealthErrorEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengHealthTimeOutEvent (
  val isTimeout: Boolean
) : YuchengHealthEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengHealthTimeOutEvent {
      val isTimeout = pigeonVar_list[0] as Boolean
      return YuchengHealthTimeOutEvent(isTimeout)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isTimeout,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengHealthTimeOutEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/**
 * Generated class from Pigeon that represents data sent in messages.
 * This class should not be extended by any user class outside of the generated file.
 */
sealed class YuchengSleepHealthEvent 
/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengSleepHealthDataEvent (
  val data: YuchengSleepHealthData
) : YuchengSleepHealthEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengSleepHealthDataEvent {
      val data = pigeonVar_list[0] as YuchengSleepHealthData
      return YuchengSleepHealthDataEvent(data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      data,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengSleepHealthDataEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengSleepHealthErrorEvent (
  val error: String
) : YuchengSleepHealthEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengSleepHealthErrorEvent {
      val error = pigeonVar_list[0] as String
      return YuchengSleepHealthErrorEvent(error)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      error,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengSleepHealthErrorEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class YuchengSleepHealthTimeOutEvent (
  val isTimeout: Boolean
) : YuchengSleepHealthEvent()
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): YuchengSleepHealthTimeOutEvent {
      val isTimeout = pigeonVar_list[0] as Boolean
      return YuchengSleepHealthTimeOutEvent(isTimeout)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      isTimeout,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is YuchengSleepHealthTimeOutEvent) {
      return false
    }
    if (this === other) {
      return true
    }
    return deepEqualsYuchengBleApi(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class YuchengBleApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          YuchengSleepType.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          YuchengDeviceState.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengSleepData.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengHealthData.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengSleepHealthData.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengSleepTimeOutEvent.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengSleepDataEvent.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengSleepDataDetail.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengSleepErrorEvent.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengDeviceStateTimeOutEvent.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengDeviceStateDataEvent.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengDeviceStateErrorEvent.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengDevice.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengDeviceTimeOutEvent.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengDeviceDataEvent.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengDeviceCompleteEvent.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengHealthDataEvent.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengHealthErrorEvent.fromList(it)
        }
      }
      147.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengHealthTimeOutEvent.fromList(it)
        }
      }
      148.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengSleepHealthDataEvent.fromList(it)
        }
      }
      149.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengSleepHealthErrorEvent.fromList(it)
        }
      }
      150.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          YuchengSleepHealthTimeOutEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is YuchengSleepType -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is YuchengDeviceState -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is YuchengSleepData -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is YuchengHealthData -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is YuchengSleepHealthData -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is YuchengSleepTimeOutEvent -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is YuchengSleepDataEvent -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is YuchengSleepDataDetail -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is YuchengSleepErrorEvent -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is YuchengDeviceStateTimeOutEvent -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is YuchengDeviceStateDataEvent -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is YuchengDeviceStateErrorEvent -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is YuchengDevice -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is YuchengDeviceTimeOutEvent -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is YuchengDeviceDataEvent -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is YuchengDeviceCompleteEvent -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is YuchengHealthDataEvent -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is YuchengHealthErrorEvent -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      is YuchengHealthTimeOutEvent -> {
        stream.write(147)
        writeValue(stream, value.toList())
      }
      is YuchengSleepHealthDataEvent -> {
        stream.write(148)
        writeValue(stream, value.toList())
      }
      is YuchengSleepHealthErrorEvent -> {
        stream.write(149)
        writeValue(stream, value.toList())
      }
      is YuchengSleepHealthTimeOutEvent -> {
        stream.write(150)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

val YuchengBleApiPigeonMethodCodec = StandardMethodCodec(YuchengBleApiPigeonCodec())


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface YuchengHostApi {
  /**
   * [scanTimeInMs] - сколько по времени сканировать (по умолчанию 3 секунды для ios и 10 для андройд)
   * Прослушивать стрим devices
   *
   * Перед сканированием нужно проверить, включен ли bluetooth и запросить разрешения
   * на bluetooth
   */
  fun startScanDevices(scanTimeInSeconds: Double?, callback: (Result<List<YuchengDevice>>) -> Unit)
  /**
   * Работает для IOS, для андройд будет просто проверка, подключен ли какой-либо девайс к сдк
   * [device] - девайс, который нужно проверить
   * Проверяет, подключен ли данный девайс
   */
  fun isDeviceConnected(device: YuchengDevice?, callback: (Result<Boolean>) -> Unit)
  /** Подключить девайс к сдк */
  fun connect(device: YuchengDevice, callback: (Result<Boolean>) -> Unit)
  fun reconnect(callback: (Result<Boolean>) -> Unit)
  /** Отключить девайс от сдк */
  fun disconnect(callback: (Result<Unit>) -> Unit)
  /**
   * Запрос на получение данных о сне
   * Можно также прослушивать стрим sleepData
   */
  fun getSleepData(startTimestamp: Long?, endTimestamp: Long?, callback: (Result<List<YuchengSleepData>>) -> Unit)
  /**
   * ТОЛЬКО IOS
   * Возвращает текущий подключенный девайс
   * Если девайс был подключен до этого и не был отключен, то сдк пытается подключиться
   * к девайсу повторно и возвращает его
   */
  fun getCurrentConnectedDevice(callback: (Result<YuchengDevice?>) -> Unit)
  fun getHealthData(startTimestamp: Long?, endTimestamp: Long?, callback: (Result<List<YuchengHealthData>>) -> Unit)
  fun getSleepHealthData(startTimestamp: Long?, endTimestamp: Long?, callback: (Result<YuchengSleepHealthData>) -> Unit)

  companion object {
    /** The codec used by YuchengHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      YuchengBleApiPigeonCodec()
    }
    /** Sets up an instance of `YuchengHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: YuchengHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.yucheng_ble.YuchengHostApi.startScanDevices$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val scanTimeInSecondsArg = args[0] as Double?
            api.startScanDevices(scanTimeInSecondsArg) { result: Result<List<YuchengDevice>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.yucheng_ble.YuchengHostApi.isDeviceConnected$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceArg = args[0] as YuchengDevice?
            api.isDeviceConnected(deviceArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.yucheng_ble.YuchengHostApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val deviceArg = args[0] as YuchengDevice
            api.connect(deviceArg) { result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.yucheng_ble.YuchengHostApi.reconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.reconnect{ result: Result<Boolean> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.yucheng_ble.YuchengHostApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.disconnect{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.yucheng_ble.YuchengHostApi.getSleepData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startTimestampArg = args[0] as Long?
            val endTimestampArg = args[1] as Long?
            api.getSleepData(startTimestampArg, endTimestampArg) { result: Result<List<YuchengSleepData>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.yucheng_ble.YuchengHostApi.getCurrentConnectedDevice$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.getCurrentConnectedDevice{ result: Result<YuchengDevice?> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.yucheng_ble.YuchengHostApi.getHealthData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startTimestampArg = args[0] as Long?
            val endTimestampArg = args[1] as Long?
            api.getHealthData(startTimestampArg, endTimestampArg) { result: Result<List<YuchengHealthData>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.yucheng_ble.YuchengHostApi.getSleepHealthData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val startTimestampArg = args[0] as Long?
            val endTimestampArg = args[1] as Long?
            api.getSleepHealthData(startTimestampArg, endTimestampArg) { result: Result<YuchengSleepHealthData> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}

private class YuchengBleApiPigeonStreamHandler<T>(
    val wrapper: YuchengBleApiPigeonEventChannelWrapper<T>
) : EventChannel.StreamHandler {
  var pigeonSink: PigeonEventSink<T>? = null

  override fun onListen(p0: Any?, sink: EventChannel.EventSink) {
    pigeonSink = PigeonEventSink<T>(sink)
    wrapper.onListen(p0, pigeonSink!!)
  }

  override fun onCancel(p0: Any?) {
    pigeonSink = null
    wrapper.onCancel(p0)
  }
}

interface YuchengBleApiPigeonEventChannelWrapper<T> {
  open fun onListen(p0: Any?, sink: PigeonEventSink<T>) {}

  open fun onCancel(p0: Any?) {}
}

class PigeonEventSink<T>(private val sink: EventChannel.EventSink) {
  fun success(value: T) {
    sink.success(value)
  }

  fun error(errorCode: String, errorMessage: String?, errorDetails: Any?) {
    sink.error(errorCode, errorMessage, errorDetails)
  }

  fun endOfStream() {
    sink.endOfStream()
  }
}
      
abstract class DevicesStreamHandler : YuchengBleApiPigeonEventChannelWrapper<YuchengDeviceEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: DevicesStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.yucheng_ble.YuchengStreamApi.devices"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = YuchengBleApiPigeonStreamHandler<YuchengDeviceEvent>(streamHandler)
      EventChannel(messenger, channelName, YuchengBleApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
abstract class SleepDataStreamHandler : YuchengBleApiPigeonEventChannelWrapper<YuchengSleepEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: SleepDataStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.yucheng_ble.YuchengStreamApi.sleepData"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = YuchengBleApiPigeonStreamHandler<YuchengSleepEvent>(streamHandler)
      EventChannel(messenger, channelName, YuchengBleApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
abstract class DeviceStateStreamHandler : YuchengBleApiPigeonEventChannelWrapper<YuchengDeviceStateEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: DeviceStateStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.yucheng_ble.YuchengStreamApi.deviceState"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = YuchengBleApiPigeonStreamHandler<YuchengDeviceStateEvent>(streamHandler)
      EventChannel(messenger, channelName, YuchengBleApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
abstract class HealthDataStreamHandler : YuchengBleApiPigeonEventChannelWrapper<YuchengHealthEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: HealthDataStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.yucheng_ble.YuchengStreamApi.healthData"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = YuchengBleApiPigeonStreamHandler<YuchengHealthEvent>(streamHandler)
      EventChannel(messenger, channelName, YuchengBleApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
abstract class SleepHealthDataStreamHandler : YuchengBleApiPigeonEventChannelWrapper<YuchengSleepHealthEvent> {
  companion object {
    fun register(messenger: BinaryMessenger, streamHandler: SleepHealthDataStreamHandler, instanceName: String = "") {
      var channelName: String = "dev.flutter.pigeon.yucheng_ble.YuchengStreamApi.sleepHealthData"
      if (instanceName.isNotEmpty()) {
        channelName += ".$instanceName"
      }
      val internalStreamHandler = YuchengBleApiPigeonStreamHandler<YuchengSleepHealthEvent>(streamHandler)
      EventChannel(messenger, channelName, YuchengBleApiPigeonMethodCodec).setStreamHandler(internalStreamHandler)
    }
  }
}
      
